name: My First CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run tests
        run: |
          python -m pip install pytest
          pytest
      
      - name: Build application
        run: |
          mkdir build
          cp app.py build/
          cp test_app.py build/
    
      - name: Upload artifacts
        uses: actions/uppload-artifact@v4
        with: 
           name: my_application
           path: build/

