name: My First CI

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        run: action/checkout@v4
      - name: Say Hello
        run: echo "Hello DevOps!"

      - name: Show system information
        run: uname -a
